package com.septiadinirahayu.currencyconverter.bean

import com.septiadinirahayu.currencyconverter.serializedName
import com.google.gson.annotations.SerializedName

class CurrencyRateResponse(
    @SerializedName("disclaimer")
    var disclaimer: String? = null,
    @SerializedName("license")
    var license: String? = null,
    @SerializedName("timestamp")
    var timestamp: Int? = null,
    @SerializedName("base")
    var base: String? = null,
    @SerializedName("rates")
    var rates: Map<Currency, Double?> = emptyMap()
) {
    fun getListCurrencyName() : List<String> {
        return rates.keys.map { it.toString() }
    }

    fun getListConversion() : List<Pair<Currency, Double?>> {
        return rates.toList()
    }

    fun getListRates() : List<Double?> {
        return rates.values.toList()
    }
}

enum class Currency {
    @SerializedName("AED") AED,
    @SerializedName("AFN") AFN,
    @SerializedName("ALL") ALL,
    @SerializedName("AMD") AMD,
    @SerializedName("ANG") ANG,
    @SerializedName("AOA") AOA,
    @SerializedName("ARS") ARS,
    @SerializedName("AUD") AUD,
    @SerializedName("AWG") AWG,
    @SerializedName("AZN") AZN,
    @SerializedName("BAM") BAM,
    @SerializedName("BBD") BBD,
    @SerializedName("BDT") BDT,
    @SerializedName("BGN") BGN,
    @SerializedName("BHD") BHD,
    @SerializedName("BIF") BIF,
    @SerializedName("BMD") BMD,
    @SerializedName("BND") BND,
    @SerializedName("BOB") BOB,
    @SerializedName("BRL") BRL,
    @SerializedName("BSD") BSD,
    @SerializedName("BTC") BTC,
    @SerializedName("BTN") BTN,
    @SerializedName("BWP") BWP,
    @SerializedName("BYN") BYN,
    @SerializedName("BZD") BZD,
    @SerializedName("CAD") CAD,
    @SerializedName("CDF") CDF,
    @SerializedName("CHF") CHF,
    @SerializedName("CLF") CLF,
    @SerializedName("CLP") CLP,
    @SerializedName("CNH") CNH,
    @SerializedName("CNY") CNY,
    @SerializedName("COP") COP,
    @SerializedName("CRC") CRC,
    @SerializedName("CUC") CUC,
    @SerializedName("CUP") CUP,
    @SerializedName("CVE") CVE,
    @SerializedName("CZK") CZK,
    @SerializedName("DJF") DJF,
    @SerializedName("DKK") DKK,
    @SerializedName("DOP") DOP,
    @SerializedName("DZD") DZD,
    @SerializedName("EGP") EGP,
    @SerializedName("ERN") ERN,
    @SerializedName("ETB") ETB,
    @SerializedName("EUR") EUR,
    @SerializedName("FJD") FJD,
    @SerializedName("FKP") FKP,
    @SerializedName("GBP") GBP,
    @SerializedName("GEL") GEL,
    @SerializedName("GGP") GGP,
    @SerializedName("GHS") GHS,
    @SerializedName("GIP") GIP,
    @SerializedName("GMD") GMD,
    @SerializedName("GNF") GNF,
    @SerializedName("GTQ") GTQ,
    @SerializedName("GYD") GYD,
    @SerializedName("HKD") HKD,
    @SerializedName("HNL") HNL,
    @SerializedName("HRK") HRK,
    @SerializedName("HTG") HTG,
    @SerializedName("HUF") HUF,
    @SerializedName("IDR") IDR,
    @SerializedName("ILS") ILS,
    @SerializedName("IMP") IMP,
    @SerializedName("INR") INR,
    @SerializedName("IQD") IQD,
    @SerializedName("IRR") IRR,
    @SerializedName("ISK") ISK,
    @SerializedName("JEP") JEP,
    @SerializedName("JMD") JMD,
    @SerializedName("JOD") JOD,
    @SerializedName("JPY") JPY,
    @SerializedName("KES") KES,
    @SerializedName("KGS") KGS,
    @SerializedName("KHR") KHR,
    @SerializedName("KMF") KMF,
    @SerializedName("KPW") KPW,
    @SerializedName("KRW") KRW,
    @SerializedName("KWD") KWD,
    @SerializedName("KYD") KYD,
    @SerializedName("KZT") KZT,
    @SerializedName("LAK") LAK,
    @SerializedName("LBP") LBP,
    @SerializedName("LKR") LKR,
    @SerializedName("LRD") LRD,
    @SerializedName("LSL") LSL,
    @SerializedName("LYD") LYD,
    @SerializedName("MAD") MAD,
    @SerializedName("MDL") MDL,
    @SerializedName("MGA") MGA,
    @SerializedName("MKD") MKD,
    @SerializedName("MMK") MMK,
    @SerializedName("MNT") MNT,
    @SerializedName("MOP") MOP,
    @SerializedName("MRU") MRU,
    @SerializedName("MUR") MUR,
    @SerializedName("MVR") MVR,
    @SerializedName("MWK") MWK,
    @SerializedName("MXN") MXN,
    @SerializedName("MYR") MYR,
    @SerializedName("MZN") MZN,
    @SerializedName("NAD") NAD,
    @SerializedName("NGN") NGN,
    @SerializedName("NIO") NIO,
    @SerializedName("NOK") NOK,
    @SerializedName("NPR") NPR,
    @SerializedName("NZD") NZD,
    @SerializedName("OMR") OMR,
    @SerializedName("PAB") PAB,
    @SerializedName("PEN") PEN,
    @SerializedName("PGK") PGK,
    @SerializedName("PHP") PHP,
    @SerializedName("PKR") PKR,
    @SerializedName("PLN") PLN,
    @SerializedName("PYG") PYG,
    @SerializedName("QAR") QAR,
    @SerializedName("RON") RON,
    @SerializedName("RSD") RSD,
    @SerializedName("RUB") RUB,
    @SerializedName("RWF") RWF,
    @SerializedName("SAR") SAR,
    @SerializedName("SBD") SBD,
    @SerializedName("SCR") SCR,
    @SerializedName("SDG") SDG,
    @SerializedName("SEK") SEK,
    @SerializedName("SGD") SGD,
    @SerializedName("SHP") SHP,
    @SerializedName("SLL") SLL,
    @SerializedName("SOS") SOS,
    @SerializedName("SRD") SRD,
    @SerializedName("SSP") SSP,
    @SerializedName("STD") STD,
    @SerializedName("STN") STN,
    @SerializedName("SVC") SVC,
    @SerializedName("SYP") SYP,
    @SerializedName("SZL") SZL,
    @SerializedName("THB") THB,
    @SerializedName("TJS") TJS,
    @SerializedName("TMT") TMT,
    @SerializedName("TND") TND,
    @SerializedName("TOP") TOP,
    @SerializedName("TRY") TRY,
    @SerializedName("TTD") TTD,
    @SerializedName("TWD") TWD,
    @SerializedName("TZS") TZS,
    @SerializedName("UAH") UAH,
    @SerializedName("UGX") UGX,
    @SerializedName("USD") USD,
    @SerializedName("UYU") UYU,
    @SerializedName("UZS") UZS,
    @SerializedName("VES") VES,
    @SerializedName("VND") VND,
    @SerializedName("VUV") VUV,
    @SerializedName("WST") WST,
    @SerializedName("XAF") XAF,
    @SerializedName("XAG") XAG,
    @SerializedName("XAU") XAU,
    @SerializedName("XCD") XCD,
    @SerializedName("XDR") XDR,
    @SerializedName("XOF") XOF,
    @SerializedName("XPD") XPD,
    @SerializedName("XPF") XPF,
    @SerializedName("XPT") XPT,
    @SerializedName("YER") YER,
    @SerializedName("ZAR") ZAR,
    @SerializedName("ZMW") ZMW,
    @SerializedName("ZWL") ZWL ;
    override fun toString(): String {
        return serializedName ?: name
    }
}


